import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {deflateSync} from 'node:zlib';
import {createApp} from '../../src/app.mjs';
import {SQLiteRepository,SupabaseRepository} from '../../src/management/repository.mjs';
import {managementService} from '../../src/management/http.mjs';
import {hashPassword,verifyPassword,sessionCookie} from '../../src/management/security.mjs';
import {managementConfig} from '../../src/management/config.mjs';
import {seedCatalogue,seededProduct,publishedSnapshot,saveProduct,publishProduct,validateProduct} from '../../src/management/catalogue.mjs';
import {normalizePNG,crc32} from '../../src/management/png.mjs';
import {products} from '../../src/catalog.mjs';
const password='local-test-only-long-passphrase-2491';
let dir,repo,server,base,config,owner,headers;
function png({width=64,height=80,metadata=false}={}){const sig=Buffer.from([137,80,78,71,13,10,26,10]);const chunk=(type,data)=>{const out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);out.write(type,4);data.copy(out,8);out.writeUInt32BE(crc32(out.subarray(4,-4)),out.length-4);return out;};const h=Buffer.alloc(13);h.writeUInt32BE(width,0);h.writeUInt32BE(height,4);h[8]=8;h[9]=6;const pixels=Buffer.alloc((width*4+1)*height,220);for(let i=0;i<height;i++)pixels[i*(width*4+1)]=0;return Buffer.concat([sig,chunk('IHDR',h),...(metadata?[chunk('tEXt',Buffer.from('Author\0Private photographer metadata'))]:[]),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
async function request(path,options={}){return fetch(base+path,{...options,headers:{...(options.admin?headers:{}),...options.headers}});}
async function json(path,method,data,extra={}){return request(path,{method,admin:true,headers:{'Content-Type':'application/json',...extra},body:JSON.stringify(data)});}
async function login(email=config.email,pass=password){const r=await request('/api/admin/login',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({email,password:pass})});const body=await r.json();return {r,body,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
before(async()=>{dir=mkdtempSync(join(tmpdir(),'khaga-management-'));repo=await SQLiteRepository.open(dir);config={enabled:true,driver:'sqlite',secure:false,email:'owner@example.test',passwordHash:await hashPassword(password),origin:'http://127.0.0.1',sessionHours:8};server=createApp({username:'',password:'',management:managementService(repo,config)});server.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}`;config.origin=base;owner=await login();headers={Cookie:owner.cookie,Origin:base,'X-CSRF-Token':owner.body.csrf};});
after(async()=>{await new Promise(r=>server.close(r));await repo.close();rmSync(dir,{recursive:true,force:true});});
test('Owner login returns a session cookie, never a password/hash',async()=>{assert.equal(owner.r.status,200);assert.match(owner.cookie,/khaga_admin_local=/);assert.match(owner.r.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.equal(owner.body.password,undefined);assert.equal(owner.body.passwordHash,undefined);assert.equal(owner.body.csrf.length,64);});
test('Public visitors cannot read or change admin records',async()=>{for(const path of ['/api/admin/products','/api/admin/session','/api/admin/audit'])assert.equal((await request(path)).status,401);assert.equal((await request('/api/admin/import',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:'{}'})).status,401);});
test('Login requires same-origin JSON and rejects sibling Slavant origins',async()=>{for(const origin of [undefined,'https://slavant.com','https://evil.test','null']){const r=await request('/api/admin/login',{method:'POST',headers:{...(origin?{Origin:origin}:{}),'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,403);}assert.equal((await request('/api/admin/login',{method:'POST',headers:{Origin:base,'Content-Type':'text/plain'},body:'{}'})).status,415);});
test('Mutations require CSRF and same origin even with a valid owner cookie',async()=>{assert.equal((await json('/api/admin/import','POST',{}, {'X-CSRF-Token':'wrong'})).status,403);assert.equal((await json('/api/admin/import','POST',{}, {Origin:'https://slavant.com'})).status,403);assert.equal((await json('/api/admin/import','POST',{}, {'Sec-Fetch-Site':'same-site'})).status,403);});
test('Import seeds seven concepts once and never overwrites edits',async()=>{assert.equal((await (await json('/api/admin/import','POST',{})).json()).inserted,7);assert.equal((await (await json('/api/admin/import','POST',{})).json()).inserted,0);assert.equal((await repo.list('product')).length,7);});
test('Saving a draft does not expose draft text or price on public API/HTML',async()=>{let r=await repo.get('product','origin-tee');const p={...r.body.draft,name:'PRIVATE draft name marker 8364',price:95500};const saved=await json('/api/admin/products/origin-tee','PUT',{version:r.version,product:p});assert.equal(saved.status,200);for(const path of ['/api/catalog','/products/origin-tee','/','/site.js']){const t=await(await request(path)).text();assert.ok(!t.includes('PRIVATE draft name marker 8364'),path);}assert.equal((await repo.get('product','origin-tee')).body.published.name,'Origin Tee');});
test('Optimistic locking prevents overwriting another edit',async()=>{const r=await repo.get('product','origin-tee');const changed={...r.body.draft,note:'Concurrent changes'};const [a,b]=await Promise.all([json('/api/admin/products/origin-tee','PUT',{version:r.version,product:changed}),json('/api/admin/products/origin-tee','PUT',{version:r.version,product:changed})]);assert.deepEqual([a.status,b.status].sort(),[200,409]);});
test('Publishing exposes the saved snapshot; unpublishing removes it from API, HTML and artwork',async()=>{let r=await repo.get('product','origin-tee');assert.equal((await json('/api/admin/products/origin-tee/publish','POST',{version:r.version})).status,200);assert.ok((await(await request('/products/origin-tee')).text()).includes('PRIVATE draft name marker 8364'));r=await repo.get('product','origin-tee');assert.equal((await json('/api/admin/products/origin-tee/unpublish','POST',{version:r.version})).status,200);assert.equal((await request('/products/origin-tee')).status,404);assert.equal((await request('/media/origin-tee/ivory/front.svg')).status,404);assert.ok(!(await(await request('/api/catalog')).text()).includes('PRIVATE draft name marker 8364'));r=await repo.get('product','origin-tee');await saveProduct(repo,r.id,r.version,seededProduct(products[0]),config.email);r=await repo.get('product',r.id);await publishProduct(repo,r.id,r.version,true,config.email);});
test('Empty and reduced catalogues render home without hard-coded array crashes',async()=>{const local=await SQLiteRepository.open(join(dir,'empty'));const app=createApp({management:managementService(local,config)});app.listen(0,'127.0.0.1');await once(app,'listening');try{const u=`http://127.0.0.1:${app.address().port}`;assert.equal((await fetch(u+'/')).status,200);assert.equal((await(await fetch(u+'/api/catalog')).json()).products.length,0);}finally{await new Promise(r=>app.close(r));await local.close();}});
test('New products begin as private drafts and survive repository reopen',async()=>{const p={...seededProduct(products[1]),id:'private-test-product',name:'Secret unpublished shirt label'};assert.equal((await json('/api/admin/products/private-test-product','PUT',{version:0,product:p})).status,200);assert.equal((await request('/products/private-test-product')).status,404);const second=await SQLiteRepository.open(dir);assert.equal((await second.get('product',p.id)).body.draft.name,p.name);assert.equal((await second.get('product',p.id)).body.published,null);await second.close();});
test('Invalid prices, size/colour injection and preorder ranges are rejected',async()=>{const p=seededProduct(products[0]);for(const bad of [{...p,price:-1},{...p,price:2.5},{...p,sizes:['<script>']},{...p,colours:['bad/../path']},{...p,palette:{...p.palette,ivory:{...p.palette.ivory,hex:'red;position:fixed'}}},{...p,variants:[{colour:'ivory',size:'S',mode:'preorder',quantity:10,dispatchMin:5,dispatchMax:2}]}])assert.throws(()=>validateProduct(bad),e=>e.status===422);});
test('Raw PNG uploader verifies pixels, strips metadata and rejects SVG/truncation/checksum errors',()=>{const clean=normalizePNG(png({metadata:true}));assert.equal(clean.width,64);assert.equal(clean.height,80);assert.ok(!clean.bytes.includes(Buffer.from('Private photographer')));assert.throws(()=>normalizePNG(Buffer.from('<svg onload=alert(1)>')),e=>e.status===422);assert.throws(()=>normalizePNG(png().subarray(0,-5)),e=>e.status===422);const bad=png();bad[40]^=1;assert.throws(()=>normalizePNG(bad),e=>e.status===422);assert.throws(()=>normalizePNG(png({width:2001,height:1})),e=>e.status===422);});
let mediaId;
test('Upload is private until attached to a published product',async()=>{const r=await request('/api/admin/media?product=origin-tee&colour=ivory',{method:'POST',admin:true,headers:{'Content-Type':'image/png'},body:png({metadata:true})});assert.equal(r.status,201);const a=await r.json();mediaId=a.id;assert.equal((await request(a.url)).status,404);const privateImage=await request(a.url,{admin:true});assert.equal(privateImage.status,200);assert.equal(privateImage.headers.get('cache-control'),'private, no-store');assert.ok(!Buffer.from(await privateImage.arrayBuffer()).includes(Buffer.from('Private photographer')));});
test('Wrong-colour attachments cannot publish another variant image',async()=>{const r=await repo.get('product','flight-tee');const p=clone(r.body.draft);p.media.navy.front={id:mediaId,alt:'Wrong owner image'};const result=await json('/api/admin/products/flight-tee','PUT',{version:r.version,product:p});assert.equal(result.status,422);});
test('Colour-specific upload and gallery order are preserved through publish and restart',async()=>{let r=await repo.get('product','origin-tee');const p=clone(r.body.draft);p.media.ivory.front={id:mediaId,alt:'Origin ivory approved front'};p.galleryOrder.ivory=['front'];r=await saveProduct(repo,r.id,r.version,p,config.email);await publishProduct(repo,r.id,r.version,true,config.email);let response=await request(`/product-media/${mediaId}.png`);assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'image/png');const page=await(await request('/products/origin-tee?colour=ivory')).text();assert.ok(page.includes(`/product-media/${mediaId}.png`));const second=await SQLiteRepository.open(dir);assert.equal((await publishedSnapshot(second)).products.find(p=>p.id==='origin-tee').media.ivory.front.id,mediaId);assert.equal((await second.getObject((await second.get('asset',mediaId)).body.objectKey)).length,normalizePNG(png({metadata:true})).bytes.length);await second.close();});
test('Revoking publication also revokes direct media delivery',async()=>{let r=await repo.get('product','origin-tee');r=await publishProduct(repo,r.id,r.version,false,config.email);assert.equal((await request(`/product-media/${mediaId}.png`)).status,404);await publishProduct(repo,r.id,r.version,true,config.email);});
test('Admin output does not include provider secrets and is never publicly cacheable',async()=>{for(const path of ['/admin','/api/admin/session','/api/admin/products','/api/admin/audit']){const r=await request(path,{admin:true});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'private, no-store');const data=await r.text();assert.ok(!data.includes(config.passwordHash));assert.ok(!data.includes('sb_secret_'));}});
test('Audit trails record product edits without password/session payloads',async()=>{const rows=await repo.audit();assert.ok(rows.some(r=>r.record_id==='origin-tee'));assert.ok(!JSON.stringify(rows).includes(password));assert.ok(!rows.some(r=>r.kind==='session'));});
test('Logout invalidates the stored session and clears cookie',async()=>{const a=await login();const r=await request('/api/admin/logout',{method:'POST',headers:{Cookie:a.cookie,Origin:base,'X-CSRF-Token':a.body.csrf,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/Max-Age=0/);assert.equal((await request('/api/admin/products',{headers:{Cookie:a.cookie}})).status,401);});
test('Changing owner credentials revokes existing sessions',async()=>{const changedConfig={...config,passwordHash:config.passwordHash.slice(0,-1)+(config.passwordHash.endsWith('0')?'1':'0')};const service=managementService(repo,changedConfig);assert.equal(await service.session({headers:{cookie:owner.cookie}}),null);});
test('Password hashing is salted, correct verification only, no plaintext storage',async()=>{const encoded=await hashPassword(password);assert.notEqual(encoded,config.passwordHash);assert.equal(await verifyPassword(password,encoded),true);assert.equal(await verifyPassword('not-the-password',encoded),false);assert.equal(await verifyPassword('x'.repeat(2000),encoded),false);});
test('Rate limiting is persisted and atomic',async()=>{const results=await Promise.all(Array.from({length:12},()=>repo.takeRate('test-limit',5,60000)));assert.equal(results.filter(Boolean).length,5);const second=await SQLiteRepository.open(dir);assert.equal(await second.takeRate('test-limit',5,60000),false);await second.close();});
test('Production cookies are host-only, Secure, HttpOnly and Strict',()=>{const cookie=sessionCookie({secure:true},'a'.repeat(64));assert.ok(cookie.startsWith('__Host-khaga_admin='));assert.ok(cookie.includes('Secure'));assert.ok(!cookie.includes('Domain='));assert.ok(cookie.includes('Path=/'));});
test('SQLite cannot be enabled on the production subdomain or inside deploy files',()=>{assert.throws(()=>managementConfig({CATALOG_DRIVER:'sqlite',APP_ORIGIN:'https://khaga.slavant.com',ALLOW_LOCAL_ADMIN:'true',KHAGA_DATA_DIR:'/tmp/devdata'}));assert.throws(()=>managementConfig({CATALOG_DRIVER:'sqlite',APP_ORIGIN:'http://localhost:3000',NODE_ENV:'production',ALLOW_LOCAL_ADMIN:'true',KHAGA_DATA_DIR:'/tmp/devdata'}));assert.throws(()=>managementConfig({CATALOG_DRIVER:'supabase',APP_ORIGIN:'http://khaga.slavant.com'}));});
test('No persistent-store config leaves preview running and admin closed',async()=>{const app=createApp({username:'',password:''});app.listen(0,'127.0.0.1');await once(app,'listening');try{const u=`http://127.0.0.1:${app.address().port}`;assert.equal((await fetch(u+'/')).status,200);assert.equal((await fetch(u+'/api/admin/session')).status,503);}finally{await new Promise(r=>app.close(r));}});
test('Live checkout remains server-blocked after owner/catalogue setup',async()=>{for(const method of ['GET','POST','PUT']){const r=await request('/api/checkout',{method,admin:true});assert.equal(r.status,403);assert.equal((await r.json()).error,'PREVIEW_ONLY');}});
test('Supabase adapter uses server secret only, exact RPC contract and private-bucket check',async()=>{const calls=[];const fetcher=async(url,opts)=>{calls.push({url,opts});if(url.endsWith('khaga_status'))return Response.json({schema:1});if(url.includes('/bucket/'))return Response.json({public:false});if(url.endsWith('khaga_get'))return Response.json({id:'origin-tee',version:1,body:{draft:{}},updated_at:123});return Response.json({allowed:true});};const sb=new SupabaseRepository({supabaseURL:'https://example.supabase.co',secretKey:'sb_secret_TEST_NOT_REAL',bucket:'khaga-product-media'},fetcher);await sb.ready();const r=await sb.get('product','origin-tee');assert.equal(r.id,'origin-tee');const call=calls.find(c=>c.url.endsWith('khaga_get'));assert.deepEqual(JSON.parse(call.opts.body),{p_kind:'product',p_id:'origin-tee'});assert.equal(call.opts.headers.apikey,'sb_secret_TEST_NOT_REAL');assert.equal(call.opts.redirect,'error');assert.ok(!call.url.includes('sb_secret'));});
test('Supabase fails closed for public buckets, timeouts, upstream errors and edit conflicts',async()=>{const cfg={supabaseURL:'https://example.supabase.co',secretKey:'sb_secret_TEST',bucket:'khaga-product-media'};const sb=new SupabaseRepository(cfg,async url=>Response.json(url.endsWith('khaga_status')?{schema:1}:{public:true}));await assert.rejects(()=>sb.ready(),e=>e.code==='PRIVATE_BUCKET_REQUIRED');for(const status of [500,401,409]){const r=new SupabaseRepository(cfg,async()=>Response.json({}, {status}));await assert.rejects(()=>r.get('product','test'),e=>e.status===(status===409?409:503));}});
test('SQL migration explicitly denies anonymous RPC/table access; no public media bucket',()=>{const sql=readFileSync(new URL('../../migrations/001_management.sql',import.meta.url),'utf8');for(const name of ['status','get','list','write','remove_session','rate','audit'])assert.match(sql,new RegExp('REVOKE ALL ON FUNCTION public\\.khaga_'+name+'\\('));assert.ok(sql.includes('ENABLE ROW LEVEL SECURITY'));assert.ok(sql.includes("'khaga-product-media','khaga-product-media',false"));});
function clone(v){return structuredClone(v);}


test('Published version never includes hidden ids and is unchanged by draft-only edits',async()=>{
 const baseline=await publishedSnapshot(repo);
 const p=seededProduct(products[0]);p.id='private-upcoming-name';
 const r=await saveProduct(repo,p.id,0,p,config.email);
 const after=await publishedSnapshot(repo);assert.equal(after.version,baseline.version);
 assert.equal(JSON.stringify(after).includes(p.id),false);
 await saveProduct(repo,p.id,r.version,{...p,note:'Not public'},config.email);
 assert.equal((await publishedSnapshot(repo)).version,baseline.version);
});
test('Storefront money formatting preserves nonzero paise',async()=>{
 const {createCatalog}=await import('../../src/catalog-core.mjs');
 assert.equal(createCatalog({}).money(319050),'₹3,190.50');
});
test('Admin sign-in cannot fall back to sending a password in the URL',()=>{
 const html=readFileSync(new URL('../../public/admin/index.html',import.meta.url),'utf8');
 assert.match(html,/<form id="login-form" method="post" action="\/api\/admin\/login">/);
 assert.match(html,/<fieldset id="login-fields" disabled>/);
});

test('Storage transaction itself rejects conflicting published colour definitions',async()=>{
 const p=seededProduct(products[0]);p.id='atomic-palette-check';p.palette.obsidian.name='A different black';
 const existing=await repo.get('product','origin-tee');
 // Origin may have been unpublished by earlier tests; publish a dedicated anchor.
 const anchor=seededProduct(products[0]);anchor.id='palette-anchor';
 await repo.cas('product',anchor.id,0,{draft:anchor,published:anchor},config.email);
 await assert.rejects(repo.cas('product',p.id,0,{draft:p,published:p},config.email),e=>e.status===422);
 assert.equal(await repo.get('product',p.id),null);
});
