import {resolve, isAbsolute} from 'node:path';
import {fileURLToPath} from 'node:url';
import {secretKeyIssue} from './secret-key-format.mjs';
const root = fileURLToPath(new URL('../../', import.meta.url));

// Diagnostics contain field names and fixed guidance only, never submitted values.
export class ConfigurationError extends Error {
  constructor(issues) {
    super(issues.map(i => `${i.field}: ${i.message}`).join(' '));
    this.name = 'ConfigurationError';
    this.code = 'CONFIGURATION_INVALID';
    this.issues = issues;
  }
}
const text = (env, name) => String(env[name] ?? '').trim();
export function managementConfig(env = process.env) {
  const issues = [];
  const add = (field, code, message) => issues.push({field, code, message});
  const bool = name => {
    const value = text(env, name).toLowerCase();
    if (value && !['true','false'].includes(value)) add(name, 'BOOLEAN_FORMAT', 'Use true or false without quotation marks.');
    return value === 'true';
  };
  const driver = text(env, 'CATALOG_DRIVER').toLowerCase() || 'preview';
  const enabled = bool('ADMIN_ENABLED');
  if (!['preview','supabase','sqlite'].includes(driver)) {
    add('CATALOG_DRIVER', 'DRIVER_FORMAT', 'Use preview or supabase without quotation marks; sqlite is local-development only.');
    throw new ConfigurationError(issues);
  }
  if (driver === 'preview') {
    if (enabled) add('ADMIN_ENABLED','PERSISTENCE_REQUIRED','Admin requires a persistent catalogue driver. Keep admin false while using preview.');
    if (issues.length) throw new ConfigurationError(issues);
    return {driver, enabled:false};
  }
  const parseOrigin = (field, httpsOnly) => {
    const value = text(env, field);
    let url;
    try { url = new URL(value); } catch { add(field,'ORIGIN_FORMAT','Enter the complete HTTPS project or site URL, not a database connection string.'); return null; }
    if (url.pathname !== '/' || url.search || url.hash || url.username || url.password || !['http:','https:'].includes(url.protocol) || (httpsOnly && url.protocol !== 'https:')) {
      add(field,'ORIGIN_FORMAT','Use a bare HTTPS origin without a path, credentials, query or quotation marks.'); return null;
    }
    return url;
  };
  const origin = parseOrigin('APP_ORIGIN', false);
  const local = origin && ['localhost','127.0.0.1','[::1]'].includes(origin.hostname);
  const localAllowed = bool('ALLOW_LOCAL_ADMIN');
  const production = text(env,'NODE_ENV').toLowerCase() === 'production';
  if (origin && origin.protocol !== 'https:' && !(local && !production && localAllowed)) add('APP_ORIGIN','HTTPS_REQUIRED','Management requires HTTPS outside explicitly enabled local development.');
  const dataDir = text(env,'KHAGA_DATA_DIR');
  if (driver === 'sqlite') {
    if (!local || production || !localAllowed) add('CATALOG_DRIVER','LOCAL_ONLY','SQLite is development-only; use Supabase for deployment.');
    if (!dataDir || !isAbsolute(dataDir)) add('KHAGA_DATA_DIR','DATA_DIRECTORY','Use an absolute local data directory outside the source/deployment directory.');
    else { const path = resolve(dataDir); if (path === root.slice(0,-1) || path.startsWith(root)) add('KHAGA_DATA_DIR','DATA_DIRECTORY','Store development data outside the source/deployment directory.'); }
  }
  let supabaseURL;
  const secretKey = text(env,'SUPABASE_SECRET_KEY');
  const bucket = text(env,'SUPABASE_MEDIA_BUCKET') || 'khaga-product-media';
  if (driver === 'supabase') {
    supabaseURL = parseOrigin('SUPABASE_URL', true);
    const keyIssue = secretKeyIssue(secretKey);
    if (keyIssue) issues.push(keyIssue);
    if (!/^[a-z0-9][a-z0-9_-]{0,99}$/.test(bucket)) add('SUPABASE_MEDIA_BUCKET','BUCKET_FORMAT','Enter the bucket ID only, such as khaga-product-media.');
  }
  const email = text(env,'ADMIN_EMAIL').toLowerCase();
  const passwordHash = text(env,'ADMIN_PASSWORD_HASH');
  if (enabled && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) add('ADMIN_EMAIL','EMAIL_FORMAT','Set a valid owner sign-in email address.');
  if (enabled && !/^scrypt\$65536\$8\$2\$[a-f0-9]{32}\$[a-f0-9]{128}$/.test(passwordHash)) add('ADMIN_PASSWORD_HASH','HASH_FORMAT','Paste the complete hash generated by npm run admin:password; preserve every dollar sign and do not paste your plain password.');
  if (issues.length) throw new ConfigurationError(issues);
  return {driver,enabled,origin:origin.origin,secure:origin.protocol==='https:',email,passwordHash,
    dataDir,supabaseURL:supabaseURL?.origin,secretKey,bucket,sessionHours:8};
}
