version = 0.1
[prod.build.parameters]
template_file = "template.yaml"
[prod.deploy.parameters]
stack_name = "khaga-commerce-prod"
resolve_s3 = false
s3_bucket = "khaga-prod-artifacts-521199095818-ap-south-1"
s3_prefix = "khaga-commerce-prod"
role_arn = "arn:aws:iam::521199095818:role/khaga-prod-cloudformation"
region = "ap-south-1"
profile = "sairn-deployer"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
parameter_overrides = "Environment=prod PaymentMode=live LiveApiApproved=false PurchasesEnabled=false FrontendOrigins=https://khaga.slavant.com"
