import {readFileSync,writeFileSync} from 'node:fs';
import {Script} from 'node:vm';
const root=new URL('../',import.meta.url);
// Intentionally small, fixed module graph; no npm runtime/bundler dependency.
// Source modules use one-line static imports and top-level named exports only.
const modules=['src/catalog.mjs','src/utils.mjs','public/cart-model.mjs','src/views.mjs','src/routes.mjs','public/app.js'];
let output=`/* KHAGA 0.3.0 — generated by scripts/build-client.mjs. Do not edit. */\n(()=>{'use strict';\n`;
for(const path of modules){
 let source=readFileSync(new URL(path,root),'utf8').replace(/^import[^\n]*;\r?\n/gm,'').replace(/^export (?=(?:const|let|function)\b)/gm,'');
 if(path==='src/views.mjs')source='const e=escapeHtml;\n'+source;
 if(/^import\b|^export\b/m.test(source))throw new Error(`Unsupported module syntax in ${path}`);
 output+='\n// '+path+'\n'+source+'\n';
}
output+='})();\n';
new Script(output,{filename:'site.js'}); // Parse verification, never executes browser code here.
writeFileSync(new URL('public/site.js',root),output);
console.log(`Browser bundle: ${Buffer.byteLength(output)} bytes; one script, no catalogue bootstrap request.`);
